# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-test

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build-test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: yarn
      - name: Bootstrap
        run: yarn lerna:bootstrap
      - name: Lint
        run: yarn lerna:lint-all
      - name: Test
        run: yarn lerna:test-all
      - name: Build
        run: yarn lerna:build-all
